In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
dataset = pd.read_csv("SocialNetworkAds.csv","\t")
dataset

User Id  Gender  Age  EstimatedSalary  Purchased
0    12343    Male   19            19000          0
1    12344    Male   35            20000          0
2    12345  Female   26            43000          0
3    12346  Female   27            76000          0
4    12347    Male   19           150000          1
5    12348  Female   27            33000          0
6    12349    Male   32            65000          0

In [3]:
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,4].values

In [4]:
x

array([[    19,  19000],
       [    35,  20000],
       [    26,  43000],
       [    27,  76000],
       [    19, 150000],
       [    27,  33000],
       [    32,  65000]], dtype=int64)

In [5]:
y

array([0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

In [7]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc_x=StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [8]:
x_train

array([[ 1.60356745, -0.79630532],
       [ 0.26726124,  0.32978301],
       [-1.06904497, -0.81641404],
       [ 0.26726124, -0.53489196],
       [-1.06904497,  1.8178283 ]])

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors = 5,metric='minkowski',p=2)
classifier.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
y_pred=classifier.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[2]], dtype=int64)

In [14]:
# visualising the training set results
from matplotlib.colors import ListedColormap
x_set,y_set = x_train,y_train
x1,x2=np.meshgrid(np.arange(start=x_set[:,0].min()-1,stop = x_set[:,0].max() + 1, step = 0.01)),np.arange(start = x_set[:,1].min()-1,stop = x_set[:, 1].max()+1,step=0.01))
    plt.contour(x1,x2,classifier.predict(np.array([x1.ravel()]).T).reshape(x1.shape), alpha= 0.75, cmap = ListedColormap(('red','green')))
    plt.xlim(x1.min(),x1.max())
    plt.ylim(x2.min(),x2.max())
    for i,j in enumerate(np.unique(y_set)):
        plt.scatter(x_set[y_set == j, 0],x_set[y_set == j ,1])
                c= ListedColormap(('red','green'))(i), label=j)
    plt.show()

IndentationError: unexpected indent (<ipython-input-14-c608678252be>, line 5)